import 'dotenv/config';

const {
   PEACH_BLOG_DEV_DATABASE_USER,
   PEACH_BLOG_DEV_DATABASE_PASSWORD,
   PEACH_BLOG_DEV_DATABASE_HOST,
   PEACH_BLOG_DEV_DATABASE_NAME,
   PEACH_BLOG_DEV_DATABASE_PORT,
   PEACH_BLOG_DEV_DATABASE_SSL
  } = process.env;
  
  export default {
    NODE_ENV: 'development',
    DATABASE_USER: PEACH_BLOG_DEV_DATABASE_USER,
    DATABASE_PASSWORD: PEACH_BLOG_DEV_DATABASE_PASSWORD,
    DATABASE_HOST: PEACH_BLOG_DEV_DATABASE_HOST,
    DATABASE_NAME: PEACH_BLOG_DEV_DATABASE_NAME,
    DATABASE_PORT: PEACH_BLOG_DEV_DATABASE_PORT,
    DATABASE_MAX_CONNECTIONS: 100,
    DEV_DATABASE_SSL: PEACH_BLOG_DEV_DATABASE_SSL
  };
  